version: '3.7'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc2
    ports:
      - 3307:3306
    volumes:
    - ./tables.sql:/tables.sql

