CREATE TABLE IF NOT EXISTS estudante (
    Uuid INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL DEFAULT '',
    cpf VARCHAR(30) NOT NULL DEFAULT '',
    celular VARCHAR(30) NOT NULL DEFAULT '',
    email VARCHAR(100) NOT NULL DEFAULT '',
    foto VARCHAR(100) NOT NULL DEFAULT '',
    senha VARCHAR(100) NOT NULL DEFAULT '',
    PRIMARY KEY(Uuid)
);

CREATE TABLE IF NOT EXISTS imovel (
    Uuid INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL DEFAULT '',
    descricao VARCHAR(100) NOT NULL DEFAULT '',
    endereco VARCHAR(100) NOT NULL DEFAULT '',
    cep VARCHAR(100) NOT NULL DEFAULT '',
    referencia VARCHAR(100) DEFAULT '',
    lat VARCHAR(30) NOT NULL DEFAULT '',
    longi VARCHAR(30) NOT NULL DEFAULT '',
    link VARCHAR(100) NOT NULL DEFAULT '',
    aluguel FLOAT NOT NULL,
    quartos INT,
    imagens VARCHAR(100) NOT NULL DEFAULT '',
    PRIMARY KEY(Uuid)
);

CREATE TABLE IF NOT EXISTS polo (
    Uuid INT NOT NULL AUTO_INCREMENT,
    endereco VARCHAR(100) NOT NULL DEFAULT '',
    cep VARCHAR(30) NOT NULL DEFAULT '',
    estado VARCHAR(30) NOT NULL DEFAULT '',
    lat VARCHAR(30) NOT NULL DEFAULT '',
    longi VARCHAR(30) NOT NULL DEFAULT '',
    PRIMARY KEY(Uuid)
);